name: variables and secrets
on: push
jobs:
    test_vars:
        runs-on: ${{ vars.JOB_RUNNER }}
        environment: staging
        env:
            JOB_ENV_VAR: ${{ vars.ENV_VAR }}
            BOULEAN_VAR: ${{ secrets.BOOLEAN_SECRET }}
        steps:
            - name: run it if the boulean is true
              if: env.BOULEAN_VAR == 'true'
              run: |
                echo "run it"
            - name: log vars
              run: |
                echo '${{ vars.JOB_RUNNER}}'
                echo '${{ env.JOB_ENV_VAR}}'
                echo '${{ env.BOULEAN_VAR}}'
        