name: variables and secrets
on: push
jobs:
    test_vars:
        environment: staging
        runs-on: ${{ vars.JOB_RUNNER }}
        env:
            JOB_ENV_VAR: ${{ vars.ENV_VAR }}
            BOULEAN_VAR: ${{ secrets.BOOLEAN_SECRET }}
        steps:
            - name: run it if the boulean is true
              if: ${{ env.BOULEAN_VAR == 'true' }}
              run: |
                echo "run it"
        